name: Deploy latest version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.11
        with:
          name: knuthuehne/jedeschule-api
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Pull latest docker images and restart
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/jedeschule/
            sudo docker-compose pull web
            sudo docker-compose up --detach --build web
            sudo docker image prune -f
